### ISSUE TITLE
Error: invalid application of ‘sizeof’ to incomplete type

### ISSUE THREAD

**Issue by blue2997** [maxdos64/BThack#1]
I have a problem when running the Makefile in the folder PoN. I think there might be some wrong in the source code. The error information are as follows.
![image](https://user-images.githubusercontent.com/64789075/102963308-b4894900-4523-11eb-85c4-6540ce950c51.png)

**Comment by blue2997** [comment]
pon.c: In function ‘responder_register_mitm_options’:
pon.c:558:56: error: invalid application of ‘sizeof’ to incomplete type ‘struct SmMitmOptions’
  558 |  struct SmMitmOptions* mitm_options = calloc(1, sizeof(struct SmMitmOptions));
      |                                                        ^~~~~~
pon.c:559:2: error: implicit declaration of function ‘sm_register_mitm_options’; did you mean ‘responder_register_mitm_options’? [-Werror=implicit-function-declaration]
  559 |  sm_register_mitm_options(mitm_options);
      |  ^~~~~~~~~~~~~~~~~~~~~~~~
      |  responder_register_mitm_options
pon.c: In function ‘initiator_register_mitm_options’:
pon.c:564:56: error: invalid application of ‘sizeof’ to incomplete type ‘struct SmMitmOptions’
  564 |  struct SmMitmOptions* mitm_options = calloc(1, sizeof(struct SmMitmOptions));
      |                                                        ^~~~~~
pon.c:565:14: error: dereferencing pointer to incomplete type ‘struct SmMitmOptions’
  565 |  mitm_options->responder_set_custom_passkey_callback = &set_custom_passkey;
      |              ^~
pon.c: In function ‘main’:
pon.c:679:2: error: implicit declaration of function ‘btstack_run_loop_posix_register_loop_callback’ [-Werror=implicit-function-declaration]
  679 |  btstack_run_loop_posix_register_loop_callback(forward_packages);
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
pon.c:683:3: error: implicit declaration of function ‘hci_transport_usb_set_address’; did you mean ‘hci_transport_usb_set_pa  683 |   hci_transport_usb_set_address(initiator_usb_device_id);
      |   hci_transport_usb_set_path
cc1: all warnings being treated as errors
Makefile:114: recipe for target 'pon.bin' failed
      |   hci_transport_usb_set_path
cc1: all warnings being treated as errors
Makefile:114: recipe for target 'pon.bin' failed
make: *** [pon.bin] Error 1
rm att_db.o att_server.o

**Comment by blue2997** [comment]
@maxdos64 @lupinglui I would appreciate it if you could help me figure it out ：）

**Comment by maxdos64** [comment]
Hi blue2997,
Thank you for pointing this out!
We are currently trying to reproduce your error state by recreating your steps so far.
First we checked out a fresh version of the repo using:

git clone git@github.com:maxdos64/BThack.git **--recurse-submodules** 

(Note the --recurse-submodules)
Then we switched to the PoN subfolder and ran make.
We were able to build the binaries this way without error.
So we suspect that there may be a difference in the version we are testing and the one you are running :-)
Maybe you didnt use the --recurse-submodules which is important to get the structure which is failing in your make?

When you run git show inside BThack/bthack it should show the following:
commit ce7f5b71137695d6a1d4de5db9967bec4d1ccf26 (HEAD, origin/bthack_mods)

To further aid you can you check if your version corresponds with this ? :)
Thank you for reaching out.

**Comment by blue2997** [comment]
@maxdos64  
Hi,
Thank you for your answer. Exactly, I didn't use the "--recurse-submodules". Now I can successfully run make in the folder "PoN", "NoP" and "full_mitm", but have problem in **"discovery".**

I get some "warning" and some "note", and finally an error:
"""
collect2: error: ld returned 1 exit status
Makefile:109: recipe for target 'discovery' failed
make: *** [discovery] Error 1
"""

**Comment by maxdos64** [comment]
Hi blue2997,

Good to hear that we resolved the first problem that way.
I wish we could make it even more prominent in the README as this will likely be an reoccuring issue for many.
We will try to come up with something there.

Regarding your new error we would certainly need a little more information.
We know that the linker failed here but not why. Could you run first `make clean` then `make` and put the whole output into a file and upload that file ?
This should give us some more indications

**Comment by blue2997** [comment]
Hi @maxdos64 ,

I feel lucky and grateful for your patient instruction. This semester, I take a Junior year course called IoT Security, during which we have an exploratory experiment.  The professor suggested us enhancing the performance of the basic experiments or replicating the experiments from papers. So I read your admirable paper and got the idea of attacking against MitM protection. Although I worried about experiment because of not familiar with the mechanism of BLE, lack of the experience of project and encountering many difficulties (e.g. setup correct environment), your reply truly encouraged me to keep trying.  Thank you very much!
Apart from that, I would like to ask two more questions:
1. What is the function of the file in **"discovery"**? According to the README, If I want to carry out an attack using "PoN" (without suppressing), the only thing I need to do is to run the "pon.bin" and add some necessary information.
2. I find it difficult to differentiate "name"  "id"  "mac". In my opinion, "name" is something people usually use to identify their devices (e.g. my phone is "HUAWEI P20"); "mac" is something like IP but used in the link layer (e.g. aa:bb:cc:dd:ee:ff); **I don't know** what is the "id" and where to find it. 


The **output file:**
[discovery.zip](https://github.com/maxdos64/BThack/files/5739177/discovery.zip)

**Comment by maxdos64** [comment]
Hi blue2998,

Glad to hear that we could raise your interest with our work. As you know experimental reproduction is a cornerstone of proper research.
Therefore, we are very happy to hear that you are attempting that.

As you know, in BLE Pairing is always conducted between an Initiator (who initiates a pairing) and a Responder (who advertises until a Initiator attempts a pairing with it). Our frameworks main task is now to make sure that a Victim Responder and Initiator are communicating only over the MitM so we can perform Method Confusion on Bluetooth.

There are two ways to use our framework.

A) using the attack.py
This will provide you with an interactive framework which allows you to program/select targets for the attack and which also permits jamming of signals (for stealthy attacks). It requires the discovery binary in order to scan for possible targets.
Most importantly, it assures that your victims will ONLY be able to find MitM devices when scanning. Hence the victim will certainly engage pairing with you instead of the legitimate devices.

B) using directly pon.bin or nop.bin
This is a less stealthy (and realistic) way of conducting the attack. Both, MitM and victim devices will show up when scanning for devices. Therefore a victim needs to actively select your mitm device in order for the attack to be succesful.

I would encourage you to first go with that option B) for a start and see if you can create a succesful MitM situation that way (and conduct a PoN or NoP attack)

Thank you for your hint on the naming problem.
**id** is the usb id of your attackers MitM Bluetooth HW (for instance your usb BLE dongle) you will get this via `lsusb`

**name** is the string which your MitM Responder will advertise itself to the victim as (this name will appear when scanning with the Victim Initiator) -> so your description was right 

Please don't hesitate to ask further questions so that we can improve our framework, feedback is very important for us. I would suggest that you direct them directly to me via maximilian.tschirschnitz@tum.de, so that we can close this issue for now :)

General: if you are interested in the nitty gritty details of BLE and really want to dive very deep i would recomend you the book "Bluetooth Low Energy: The Developer's Handbook" by Robin Heydon.
